### ISSUE TITLE
List of approved cipher suites

### ISSUE THREAD

**Issue by cheffo** [governmentbg/egov-requirements#4]
Здравейте има ли някаква причина списъка с разрешените комбинации да не включва следните cipher suites:

TLS_DHE_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA
TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384

Аз бих позволил повече cupher suites, като разбира се препоръчан е
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
а за ECDH CURVE - secp384r1

**Comment by ignisf** [comment]
Здрасти,

Да, причините са няколко:
1. TLS 1.3 по всяка вероятност няма да позволява използването на AES CBC[1].
2. Черният списък на шифрите на HTTP/2 включва всички AES CBC комплекти от шифри[2].
3. ENISA препоръчва използването само на AEAD комплекти от шифри[3].
4. NIST изисква употребата на GCM комплекти от шифри, ако се използва TLS 1.2, за съвместимост с NSA Suite B[4].

[1] https://tlswg.github.io/tls13-spec/#rfc.appendix.A.4
[2] https://tools.ietf.org/html/rfc7540#appendix-A
[3] Страница 9 от https://www.enisa.europa.eu/activities/identity-and-trust/library/deliverables/algorithms-key-size-and-parameters-report-2014
[4] https://tools.ietf.org/html/rfc6460#section-4

**Comment by ignisf** [comment]
Не мога да цитирам източник, който препоръчва неизползването на Camellia, освен че Suite B не включва Camellia[1].

Субективните ми наблюдения (disclaimer: IANAC I am not a cryptographer) са:
- Camellia не е изследван, колкото AES
- Повечето клиенти, които поддържат Camellia, поддържат и AES. Следователно почти никога не се достига до използване на Camellia, защото комплектите от шифри, включващи AES са в общия случай по-приоритетни.
- Що се отнася до производителност, Camellia и AES са приблизително еднакви на система, която не предоставя ускорение на AES.
- Липсват системи, които предоставят ускорение на Camellia.
- В случай, че бъде открит катастрофален дефект в AES, пак ще е нужно да се направи промяна в конфигурацията на всички засегнати системи. Изваждането на AES от списъка на позволените за системата шифри и изваждането на AES от списъка и заместването му с Camellia не би трябвало да се различават по сложност.

Единственият сценарий, за който се сещам, в който би било положително, ако и AES и Camellia са позволени, е при откриване на фатален дефект в AES и последващо блеклистване на AES от разработчиците на браузърите.

[1] https://tools.ietf.org/html/rfc6460#section-3

Edit: Правилният цитат за Suite B е https://tools.ietf.org/html/rfc6460

**Comment by cheffo** [comment]
Доста изчерпателен отговор :) Мерси.

**Comment by ignisf** [comment]
За нищо :)
